---
version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      time: "06:00"
      timezone: Europe/London
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      time: "06:00"
      timezone: Europe/London
      interval: daily
    labels:
      - dependencies
