---
# Copyright © 2021-2024 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI
on:
  push:
    branches-ignore: dependabot/**
  pull_request:
  schedule:
    - cron: '30 12 * * 5'

jobs:
  overcommit:
    name: Overcommit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and sign
        run: |
          sudo gem install overcommit --no-document
          overcommit --sign
          overcommit --sign pre-commit

      - name: Run hooks
        env:
          GIT_AUTHOR_NAME: Dummy
          GIT_AUTHOR_EMAIL: dummy@example.com
          SKIP: GradleCheck
        run: overcommit --run

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
          dependency-graph: ${{ github.ref == 'refs/heads/master' &&
                                'generate-and-submit' || 'disabled' }}
        env:
          PKG_USERNAME: github-actions
          PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
