---
# Copyright © 2021-2024 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Release
on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: play-store-release
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate release bundle
        run: ./gradlew bundleRelease
        env:
          PKG_USERNAME: github-actions
          PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign release bundle
        run: |
          echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 -d > upload.p12
          jarsigner -keystore upload.p12 \
                    -storepass '${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}' \
                    app/build/outputs/bundle/release/app-release.aab upload
          rm upload.p12

      - name: Upload signed bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Write release notes to file
        run: |
          mkdir relnotes
          echo '${{ github.event.release.body }}' \
            | perl -pe 's/^ ?[+*-] /  • /' > relnotes/whatsnew-en-GB

      - name: Upload bundle to Play Store
        # yamllint disable-line rule:line-length
        uses: r0adkll/upload-google-play@935ef9c68bb393a8e6116b1575626a7f5be3a7fb
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.nerdoftheherd.stereoviewer
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          whatsNewDirectory: relnotes
          track: internal
