---
# Copyright © 2021-2023 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: play-store-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Generate release bundle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bundleRelease
        env:
          PKG_USERNAME: github-actions
          PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign release bundle
        run: |
          echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 -d > upload.p12
          jarsigner -keystore upload.p12 \
                    -storepass '${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}' \
                    app/build/outputs/bundle/release/app-release.aab upload
          rm upload.p12

      - name: Upload signed bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: app/build/outputs/bundle/release/app-release.aab
